### ISSUE TITLE
Modify to also model D1 transitions

### ISSUE THREAD

**Issue by ahrendsen** [DawesLab/rubidium#1]
Hello Andrew Dawes,

My name is Karl Ahrendsen, I'm currently a graduate student at the University of Nebraska-Lincoln. I'm working on a Rubidium project over this summer and in researching the project, came across references to Paul Siddons' Mathematica code. It appears to have been removed from its original location, so I was glad to see that you had recreated it in Python.

My work focuses on the D1 transition of Rb, so I plan on trying to extend your code to work for that purpose. 

Thanks again,
Karl Ahrendsen

**Comment by amcdawes** [comment]
Karl,
I have made some progress working on a D1 version so please let me know if you have any trouble. I will try to get what I have into a working state and posted. Also, if you are familiar with github, it would be great if you submit a pull request for your D1 code so I can add it for others to use as well.

Best,
Andy

PS I am working on an iOS app that does some useful calculations for Rb research (and model spectra like this code). I'll post a link when it is ready.

**Comment by ahrendsen** [comment]
Andy,

Sorry if I'm missing something really obvious here. Generating the D1 version of this code would just be a matter of exchanging the appropriate variables from the D2 values to the D1 values, right? Specifically:

The probing wavelength
Excited state decay rate
transition strength and detuning factors
Functions called within TotalChiXX() to correspond to the new ground and excited levels

Are there other adjustments that need to be made beyond just changing the variables?

The iOS app sounds cool, I'll be sure to check it out when it's available.

Karl

**Comment by amcdawes** [comment]
I believe that's all that needs to be fixed. I have some time tonight, I'll give it a shot. It's basically a couple hours with Steck's papers and running the numbers for the various line de-tunings etc.

**Comment by amcdawes** [comment]
I've pushed code for D1 in the script rubidiumD1.py, take a look and open any issues that you find. Thanks for giving me the extra nudge to get this done. Turns out we are using D1 a fair bit now and will need these models soon. Closed and fixed by d5a4082
