### ISSUE TITLE
Running RubidiumD2.py script on its own

### ISSUE THREAD

**Issue by ahrendsen** [DawesLab/rubidium#2]
Hello, 

When running the RubidiumD2.py script, no profile or data is output. Should the current main() function be placed instead in the if **name**== 'main': portion of the script? Or perhaps more elegantly, call main() from here? I think this would be the default behavior that I would expect from the program.

Karl

**Comment by amcdawes** [comment]
Also victim of the interrupted edit. This has been fixed by da375db and should now work if you pull a fresh copy from github.
